all:
  # PLAYER GROUPS
  GROUP_A: 1
  GROUP_B: 2

  # PLAYER STATES
  STATE_BEGINNER: 1
  STATE_AMATEUR: 2
  STATE_ADVANCED: 3
  STATE_EXPERT: 4

  # FINANCIAL KNOWLEDGE
  TYPE_INTEREST: "INTEREST"
  TYPE_DIVERSIFICATION: "DIVERSIFICATION"

  # CONSUMER BEHAVIOUR
  TYPE_RISK: "RISK"
  TYPE_ANCHORING: "ANCHORING"
  TYPE_MENTAL_BOOKKEEPING: "MENTAL_BOOKKEEPING"
  TYPE_FRAMING: "FRAMING"

  # SELF CONTROL
  TYPE_SAVINGS_TARGET: "SAVINGS_TARGET"
  TYPE_SAVINGS_SUPPORTED: "SAVINGS_SUPPORTED"
  TYPE_SELF_COMMITMENT: "SELF_COMMITMENT"
  TYPE_PROCRASTINATION: "PROCRASTINATION"

  # TEMPLATE PATHS
  VIEWS_PATH: "views/"

  # CODE STORAGE KEY
  CODE_STORAGE_KEY: "gQL4tGLK2EqMjm5A"

dev:
  # change to your real webserver to test whole
  # functionality of backend (server sent events)
  API_URL: "http://localhost:8000/api"
prod:
  API_URL: "https://symfony-1010894370596.europe-west1.run.app/api"
